-- SCRIPT DE CREACIÓN DE BASE DE DATOS (SIN PREFIJOS DE ESQUEMA)

-- 1. TABLA: CARRERA
CREATE TABLE CARRERA (
    CODIGOCARRERA VARCHAR2(20 BYTE) NOT NULL,
    NOMBRE        VARCHAR2(200 BYTE),
    CONSTRAINT CARRERA_PK PRIMARY KEY (CODIGOCARRERA)
);

-- 2. TABLA: PLANCARRERA
CREATE TABLE PLANCARRERA (
    CODIGOCARRERA VARCHAR2(20 BYTE) NOT NULL,
    PLANCARRERA   NUMBER(4,0) NOT NULL,
    CONSTRAINT PLANCARRERA_PK PRIMARY KEY (CODIGOCARRERA, PLANCARRERA),
    CONSTRAINT PLANCARRERA_FKCARRERA FOREIGN KEY (CODIGOCARRERA) 
        REFERENCES CARRERA (CODIGOCARRERA)
);

-- 3. TABLA: MATERIA
CREATE TABLE MATERIA (
    CODIGOCARRERA  VARCHAR2(20 BYTE) NOT NULL,
    PLANCARRERA    NUMBER(4,0) NOT NULL,
    CODIGOMATERIA  VARCHAR2(20 BYTE) NOT NULL,
    NOMBRE         VARCHAR2(200 BYTE),
    UV             NUMBER(2,0),
    CICLO          VARCHAR2(10 BYTE),
    CONSTRAINT MATERIA_PK PRIMARY KEY (CODIGOCARRERA, PLANCARRERA, CODIGOMATERIA),
    CONSTRAINT MATERIA_FKPLANCARRERA FOREIGN KEY (CODIGOCARRERA, PLANCARRERA) 
        REFERENCES PLANCARRERA (CODIGOCARRERA, PLANCARRERA)
);

-- 4. TABLA: DOCENTE
CREATE TABLE DOCENTE (
    CODIGO    VARCHAR2(200 BYTE) NOT NULL,
    NOMBRES   VARCHAR2(200 BYTE),
    APELLIDOS VARCHAR2(200 BYTE),
    CONSTRAINT DOCENTE_PK PRIMARY KEY (CODIGO)
);

-- 5. TABLA: GRUPO
CREATE TABLE GRUPO (
    CODIGOCARRERA  VARCHAR2(20 BYTE) NOT NULL,
    PLANCARRERA    NUMBER(4,0) NOT NULL,
    CODIGOMATERIA  VARCHAR2(20 BYTE) NOT NULL,
    GRUPO          NUMBER(2,0) NOT NULL,
    CUPO           NUMBER(3,0),
    ANHOCICLO      VARCHAR2(6 BYTE),
    CODIGODOCENTE  VARCHAR2(200 BYTE),
    CONSTRAINT GRUPO_PK PRIMARY KEY (CODIGOCARRERA, PLANCARRERA, CODIGOMATERIA, GRUPO),
    CONSTRAINT GRUPO_FKMATERIA FOREIGN KEY (CODIGOCARRERA, PLANCARRERA, CODIGOMATERIA) 
        REFERENCES MATERIA (CODIGOCARRERA, PLANCARRERA, CODIGOMATERIA),
    CONSTRAINT GRUPO_FKDOCENTE FOREIGN KEY (CODIGODOCENTE) 
        REFERENCES DOCENTE (CODIGO)
);

-- 6. TABLA: ALUMNO
CREATE TABLE ALUMNO (
    CARNET          VARCHAR2(10 BYTE) NOT NULL,
    NOMBRES         VARCHAR2(100 BYTE),
    APELLIDOS       VARCHAR2(200 BYTE),
    FECHANACIMIENTO DATE,
    DUI             VARCHAR2(20 BYTE),
    SEXO            VARCHAR2(1 BYTE),
    CONSTRAINT ALUMNO_PK PRIMARY KEY (CARNET),
    CONSTRAINT ALUMNO_DUI UNIQUE (DUI)
);

-- 7. TABLA: TIPOFIN
CREATE TABLE TIPOFIN (
    TIPOFIN   NUMBER(4,0) NOT NULL,
    NOMBREFIN VARCHAR2(200 BYTE),
    CONSTRAINT TIPOFIN_PK PRIMARY KEY (TIPOFIN)
);

-- 8. TABLA: PERTENECE
CREATE TABLE PERTENECE (
    CARNET         VARCHAR2(10 BYTE) NOT NULL,
    CODIGOCARRERA  VARCHAR2(20 BYTE) NOT NULL,
    PLANCARRERA    NUMBER(4,0) NOT NULL,
    FECHAINICIO    DATE,
    FECHAFIN       DATE,
    TIPOFIN        NUMBER(4,0),
    CONSTRAINT PERTENECE_PK PRIMARY KEY (CARNET, CODIGOCARRERA, PLANCARRERA),
    CONSTRAINT PERTENECE_FKALUMNO FOREIGN KEY (CARNET) 
        REFERENCES ALUMNO (CARNET),
    CONSTRAINT PERTENECE_FKPLANCARRERA FOREIGN KEY (CODIGOCARRERA, PLANCARRERA) 
        REFERENCES PLANCARRERA (CODIGOCARRERA, PLANCARRERA),
    CONSTRAINT PERTENECE_FKTIPOFIN FOREIGN KEY (TIPOFIN) 
        REFERENCES TIPOFIN (TIPOFIN)
);

-- 9. TABLA: EXPEDIENTE
CREATE TABLE EXPEDIENTE (
    CODIGOCARRERA  VARCHAR2(20 BYTE) NOT NULL,
    PLANCARRERA    NUMBER(4,0) NOT NULL,
    CODIGOMATERIA  VARCHAR2(20 BYTE) NOT NULL,
    CARNET         VARCHAR2(10 BYTE) NOT NULL,
    NOTA           NUMBER(5,2),
    ESTADO         VARCHAR2(20 BYTE),
    CONSTRAINT EXPEDIENTE_PK PRIMARY KEY (CODIGOCARRERA, PLANCARRERA, CODIGOMATERIA, CARNET),
    CONSTRAINT EXPEDIENTE_FKMATERIA FOREIGN KEY (CODIGOCARRERA, PLANCARRERA, CODIGOMATERIA) 
        REFERENCES MATERIA (CODIGOCARRERA, PLANCARRERA, CODIGOMATERIA),
    CONSTRAINT EXPEDIENTE_FKALUMNO FOREIGN KEY (CARNET) 
        REFERENCES ALUMNO (CARNET)
);